### ISSUE TITLE
GET methods params should use $http.get(url, {params: paramObj}) to be more easily interceptable 

### ISSUE THREAD

**Issue by facultymatt** [FacultyCreative/ngActiveResource#10]
ngActive GET requests should use the following syntax: 

```
$http.get(url, {params: paramObj})
```

In the above example we pass in the `paramObj` as `params` to the request config. Angular then handles stringifying them and appending the the url. This eliminates the need to do this within ngAactiveResource. More importantly, it gives us access to the params within our interceptors within the request(config) provider as `config.params`. This allows us to manipulate the params before sending them off - for example we could change the request to POST, delete the params, and add them instead to `data.body`.

**Comment by brettshollenberger** [comment]
Now released on 0.6.2
