### ISSUE TITLE
djson is not defined

### ISSUE THREAD

**Issue by brayniverse** [FacultyCreative/ngActiveResource#15]
I keep getting the following error:

> ReferenceError: djson is not defined

Any idea why? Is there a dependency that I haven't included somewhere?

**Comment by brettshollenberger** [comment]
Have you loaded the json/json.js file? The most recent release (this morning) has everything compiled into a single file, so you should no longer need to load files separately. If you're still seeing this error, please let me know the circumstances so we can debug it :)

**Comment by brayniverse** [comment]
I was loading json.js after ngActiveResource. Thanks for your speedy response :)
