### ISSUE TITLE
TypeError: Object Dashboard has no method 'hyphenate'

### ISSUE THREAD

**Issue by brayniverse** [FacultyCreative/ngActiveResource#16]
Sorry, I tried to figure this one out by searching through your sourcecode but I had no luck.

Any idea what I've forgotten to get this error.

**Comment by brettshollenberger** [comment]
ActiveSupport dependency; this I will be incorporating into a later release. Thanks for pointing it out.

**Comment by brayniverse** [comment]
While I'm at it then lodash isn't included in the current release either.

**Comment by brettshollenberger** [comment]
Also noted. ActiveSupport is my code, so I don't expect anyone to have it loaded; with lodash we'll probably want to conditionally load it.

**Comment by AlJohri** [comment]
+1 on this issue, just went through this same process of dependency resolution

**Comment by brayniverse** [comment]
@AlJohri yea I opened another issue/pr where I'm adding the dependencies to the install docs. Aside from json.js, lodash and active support did you have any other problems installing?

**Comment by AlJohri** [comment]
@brayniverse, nope that was all!

**Comment by brayniverse** [comment]
Install docs have been updated, therefore I'm closing this issue as I don't foresee anybody else having the same problem.
