### ISSUE TITLE
Sideload Resources [feature]

### ISSUE THREAD

**Issue by brayniverse** [FacultyCreative/ngActiveResource#25]
Making a http request per resource isn't always desired. Any chance sideloading is on your roadmap?

Take the following data structure for example:

``` json
{
  "title": "example post",
  "body": "...",
  "comments": [/* embedded comments */]
}
```

I can envision two possible apis for this to work.
1. Automatically match any indexes that match relationship names defined in models.
2. Have a method on the api module where you define indexes to match.

``` javascript
Model.api.embedable({
  'comments': 'comments'
});
```

Is this worth investigating further?

**Comment by brayniverse** [comment]
Also this would offer the developer more flexibility because we have no control over `{overEager: true}` as far as I'm aware, this way we provide all the related data in one hit.

**Comment by brettshollenberger** [comment]
In the context of API design, can you explain this idea further, or provide some reading that might help me understand? As far as I know, there's no way to signal to an endpoint that you want it to load certain associations; the service may or may not provide that functionality. If there were a common way for the service and client to signal whether or not they wanted associated resources (client), and whether or not all associated resources were loaded (server), then we could definitely scale back the HTTP requests. So far I'm not connecting the dots on what you have in mind :)

**Comment by brayniverse** [comment]
My situation is probably too specific to be used as a guideline for this feature but I'm using query string parameters to signal what to embed like so `http://localhost:8000/api/posts/1?embed=comments`.

I think ngActiveResource should keep clear of dictating how to signal to the server, this feature would work much better if that was left to the developers discretion and instead turned it's attention towards providing the developer a way to indicate when a related model is embedded in the response.

There are two noteworthy repositories [ember.js data (client)](https://github.com/emberjs/data) and [fractal (server)](https://github.com/thephpleague/fractal), which both cover what I'm proposing. I will try and find some further material and formulate a better explanation.

**Comment by brettshollenberger** [comment]
@brayniverse I'm realizing more and more just how disparate APIs can be. I see what you're saying. Let's figure out how to approach it.
