### ISSUE TITLE
Crazy amounts of errors

### ISSUE THREAD

**Issue by JoshuaNovak919** [FacultyCreative/ngActiveResource#35]
I followed the installation instructions and received nothing but errors. Looks like the name to include ngActiveResource is now 'ActiveResource', even though the read me says ngActiveResource. After changing it I am now receiving the error 'has no method 'hyphenate''.

**Comment by JoshuaNovak919** [comment]
Woops, after going through your documentation it seems you need to include active-support to fix the hyphenate issue. Now that I did that and changed 'ngActiveResource' to 'ActiveResource' it works fine. You may just want to update the docs to show the name change.

**Comment by brettshollenberger** [comment]
Thanks for the note @JoshuaNovak919. I've updated that documentation, and we're working on building in dependencies for later releases.

**Comment by JoshuaNovak919** [comment]
Thanks! For now you may want to add any other dependencies that need to be included to the docs. I received more errors until I included async etc.

**Comment by brettshollenberger** [comment]
@JoshuaNovak919; apologies, it's another documentation challenge, which told you to load 0.7.0. The latest version has these dependencies bundled in the `dist` folder versions of the files.
