### ISSUE TITLE
Using a Serializer & Adapter to interact with custom APIs

### ISSUE THREAD

**Issue by jonkoops** [FacultyCreative/ngActiveResource#57]
I'm currently looking to implement ngActiveResource, but am unable to make it communicate with our API because ours greatly deviates from the conventions assumed in the docs. Which would basically force me to fork the repo and change the code to comply with the structure we're using.

Some kind of Adapter & Serializer base class would be an ideal situation. This would allow developers to write a minimal amount of code to make their APIs work with ngActiveResource. These would essentially be the same concept used in Ember Data, see [Adapter](http://emberjs.com/guides/models/#toc_adapter) & [Serializer](http://emberjs.com/guides/models/#toc_serializer) from the Ember docs.

**Comment by AlJohri** [comment]
Duplicate #18
