### ISSUE TITLE
Add a hasCache() method or somthing similar

### ISSUE THREAD

**Issue by facultymatt** [FacultyCreative/ngActiveResource#9]
Since `Sensor.cached.length` doesn't work as expected, let's create a method that abstracts Object.keys whatever.

**Comment by brettshollenberger** [comment]
Since Model.cached is an object, its length property works as expected in Javascript (e.g. it has none). I might even consider removing this from the API, as I see no reason to expose the cache to users. This functionality was really developed to be used internally.

**Comment by facultymatt** [comment]
Worth noting you can now user `isEmpty()` as per https://github.com/FacultyCreative/ngActiveResource/commit/db2c7a8a2aa77421173a3165e90c9e061e1ff807
